services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lettereater-api
    networks:
      - backend-network

  lettereater-api:
    build:
      context: ./LetterEater
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - backend-network

  catalog-service:
    build:
      context: ./CatalogService
    environment:
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - backend-network

  order-service:
    build:
      context: ./OrderService
    environment:
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - backend-network

  user-service:
    build:
      context: ./UserService
    environment:
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge